### ISSUE TITLE
System.ArgumentException: An item with the same key has already been added.

### ISSUE THREAD

**Issue by danwalmsley** [aelij/IgnoresAccessChecksToGenerator#1]
I got this when trying to gain access to Roslyn api...

<PropertyGroup>
    <InternalsAssemblyNames>Microsoft.CodeAnalysis.Features;Microsoft.CodeAnalysis.Workspaces</InternalsAssemblyNames>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="IgnoresAccessChecksToGenerator" Version="0.1.0" PrivateAssets="all" />

can be reproduced with this commit of avalonstudio...

https://github.com/VitalElement/AvalonStudio/tree/roslyn-access-without-sign

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "GenerateDepsFile" task failed unexpectedly.
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.NET.Build.Tasks.SingleProjectInfo.CreateProjectReferenceInfos(IEnumerable`1 referencePaths, IEnumerable`1 referenceSatellitePaths)
   at Microsoft.NET.Build.Tasks.GenerateDepsFile.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	AvalonStudio.Projects.OmniSharp	C:\Program Files\dotnet\sdk\2.0.0-preview2-006497\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.Sdk.targets	109	
```

**Comment by aelij** [comment]
Hmm it’s weird because it doesn’t even fail in my task’s code.

Can you try adding the roots packages assemblies as well?
Microsoft.CodeAnalysis

**Comment by danwalmsley** [comment]
I think it already is?

```
<PropertyGroup>
    <InternalsAssemblyNames>Microsoft.CodeAnalysis.Features;Microsoft.CodeAnalysis.Workspaces</InternalsAssemblyNames>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="IgnoresAccessChecksToGenerator" Version="0.1.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Build" Version="15.3.0-preview-000388-01" />
    <PackageReference Include="Microsoft.CodeAnalysis" Version="2.3.1" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Features" Version="2.3.1" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="2.3.1" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="2.3.1" />
    <PackageReference Include="RestSharp.NetCore" Version="105.2.4-rc4-24214-01" />
  </ItemGroup>
```

**Comment by danwalmsley** [comment]
Oh to the InternalsAssemblyNames attribute! just trying now

**Comment by aelij** [comment]
I meant add it in the `InternalsAssemblyNames`. It should be there anyhow since there are base types in there, and the accessibility needs to be the same for it to work properly.

**Comment by aelij** [comment]
I think I know what the problem is. I'm adding the new reference assemblies without removing the old ones. Perhaps the problem is in the `netcoreapp2.0` SDK (which I haven't tested). Anyway it's an easy fix.

**Comment by danwalmsley** [comment]
@aelij let me know when its ready, and I will test, adding Microsoft.CodeAnalysis didn't change anything.

**Comment by danwalmsley** [comment]
@aelij gentle reminder to submit fix  ;)

**Comment by aelij** [comment]
@danwalmsley Try now :)

**Comment by danwalmsley** [comment]
Thanks It seems to work now 👍
