### ISSUE TITLE
unknown build error

### ISSUE THREAD

**Issue by impoetk** [aelij/IgnoresAccessChecksToGenerator#10]
I get the following error by using the nuget in a wpf net framework 4.8 project

error MC1000: Unknown build error, 'Could not load type 'System.Runtime.CompilerServices.RestrictedInternalsVisibleToAttribute' from assembly 'Microsoft.CodeAnalysis.Workspaces, Version=3.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' because the method '.ctor' has no implementation (no RVA).'

**Comment by aelij** [comment]
Duplicate of #6

**Comment by aelij** [comment]
As a workaround, use this tool on a non-WPF project (one that doesn't build xaml) and reference it.
