### ISSUE TITLE
Monodevelop: analyzer uses original reference instead of generated one

### ISSUE THREAD

**Issue by myocytebd** [aelij/IgnoresAccessChecksToGenerator#14]
Building works flawlessly, but monodevelop seems to use original reference for analyzer (auto completion etc.).  
Is there a way to solve it automatically in project files without manually change reference after generation?  
Or did I miss something?  

In .csproj:  
```
    <InternalsAssemblyNames>Assembly-CSharp;</InternalsAssemblyNames>
...
    <Reference Include="Assembly-CSharp">
      <HintPath>path\to\original\Assembly-CSharp.dll</HintPath>
    </Reference>
```
(I have little knowledge of around .csproj and .net build flow)

**Comment by aelij** [comment]
Sorry I don't know how monodevelop works. Does it happen only for `Reference`s or also for `PacakgeReference`s?

**Comment by myocytebd** [comment]
It was too long ago and I could not remember the details. Let me close it. (and monodevelop has been dead for long)
