### ISSUE TITLE
internal properties

### ISSUE THREAD

**Issue by npolyak** [aelij/IgnoresAccessChecksToGenerator#20]
Friends, is there any reason you have not included internal properties to make them public?

I modified the code on my own machine by adding the following to the CreatePublicAssembly method's inner loop

            foreach(var prop in type.Properties)
            {
                if (prop.GetMethod != null)
                {
                    if ( prop.GetMethod.IsAssembly || 
                         prop.GetMethod.IsFamilyOrAssembly || 
                         prop.GetMethod.IsFamilyAndAssembly)
                    {
                        prop.GetMethod.IsPublic = true;
                    }
                }
                if (prop.SetMethod != null)
                {
                    if (prop.SetMethod.IsAssembly ||
                         prop.SetMethod.IsFamilyOrAssembly ||
                         prop.SetMethod.IsFamilyAndAssembly)
                    {
                        prop.SetMethod.IsPublic = true;
                    }
                }
            }         

Is it possible to add it to the package?

**Comment by aelij** [comment]
It's already supported, as properties (and events) are included in the Methods property in Cecil (unlike Reflection).

**Comment by npolyak** [comment]
I modified your project to add some functionality that I need and created a new repo while giving you the proper attribution. Please, take a look at [DotNetBinaryAdjuster](https://github.com/npolyak/DotNetBinaryAdjuster)

**Comment by weltkante** [comment]
It sounds like your fork is permanently patching assemblies, not just providing access to internals at compiletime while still running the original assembly at runtime?

**Comment by npolyak** [comment]
> It sounds like your fork is permanently patching assemblies, not just providing access to internals at compiletime while still running the original assembly at runtime?

To tell you the truth, I am not sure. It works for me and I thought I followed everything from IgnoresAccessChecksToGenerator. If you think I did something wrong, please, be specific - it could have easily happened since I do not know much about mono.cecil. 

Thanks

**Comment by npolyak** [comment]
> It sounds like your fork is permanently patching assemblies, not just providing access to internals at compiletime while still running the original assembly at runtime?

I just realized - my attempt at virtualization did not work - the old method is still being called. I guess it is not as good as I hoped it would be.

**Comment by weltkante** [comment]
> I just realized - my attempt at virtualization did not work

Ye that was what I meant, things like that require permanent patching, since it affects runtime and not compile time.

**Comment by npolyak** [comment]
> > I just realized - my attempt at virtualization did not work
> 
> Ye that was what I meant, things like that require permanent patching, since it affects runtime and not compile time.

Any ideas or links on how to patch it permanently - e.g. create another dll and use it instead of the original one?

**Comment by weltkante** [comment]
> > > I just realized - my attempt at virtualization did not work
> > 
> > 
> > Ye that was what I meant, things like that require permanent patching, since it affects runtime and not compile time.
> 
> Any ideas or links on how to patch it permanently - e.g. create another dll and use it instead of the original one?

Well, you just do the same, use Mono.Cecil during build time to rewrite the assembly, but not just for the compiler input. Frameworks doing that exist but I never used them, check maybe https://stackoverflow.com/questions/189359/what-is-il-weaving for ideas on where to look.

**Comment by npolyak** [comment]
Thanks man, I work with Avalonia - which is open source under MIT license, so I do not expect any copyright problems
Eventually in order to avoid the weaving somersaults and jumping jacks, Avalonia will have to make its code a bit easier to modify it without resorting to extreme measures or without re-writing its packages.

**Comment by npolyak** [comment]
@weltkante , sorry, as I mentioned before I am pretty new to Cecil. It seems like the modified assembly is saved by the call to 

    assembly.Write(target);

But even if I use that saved assembly, it is not performing the override. What am I doing wrong? Perhaps you can recommend some websites where cecil is explained?

**Comment by weltkante** [comment]
That should work, if it doesn't something went wrong with your modifications. Can't really recommend any guides since I just learned it by trial & error myself and reading code like this repo. What I'm usually doing is writing a console app that loads the assembly, modifies it, and writes it back under a different name - then use ilspy to verify my edits. If I need a reference to how something needs to look at the IL level I write a dummy c# project just doing the one thing I need to know how it looks and open the assembly in ILSpy, then replicate it in Mono.Cecil. Thats relly all there is to it as far as I'm concerned.

**Comment by npolyak** [comment]
Thanks @weltkante !
