### ISSUE TITLE
Does not open access to private methods

### ISSUE THREAD

**Issue by sturlath** [aelij/IgnoresAccessChecksToGenerator#5]
Hi I was trying this out on [Strathweb.Samples.CSharp.NoVisibilityChecks](https://github.com/filipw/Strathweb.Samples.CSharp.NoVisibilityChecks) and it works for classes but I **can't get it to work with the private method** [ Calculate()](https://github.com/filipw/Strathweb.Samples.CSharp.NoVisibilityChecks/blob/master/Calculator/Calculator.cs). 

Shouldn't it work there also? 

![image](https://user-images.githubusercontent.com/2386572/49283919-f6517d80-f48a-11e8-9400-0bcda13dc76d.png)

**Comment by aelij** [comment]
AFAIK the CLR only supports calling internal members with this attribute. So the Publicize task only transforms `internal` to `public`. But you can experiment, with the code perhaps it would work with `private` as well.

**Comment by sturlath** [comment]
Thanks. I’ll look into it now that I know what the problem area is.

Somehow he manages to do it here https://www.strathweb.com/2018/10/no-internalvisibleto-no-problem-bypassing-c-visibility-rules-with-roslyn/ (evenhough I havent gotten that to work either 🙈)

**Comment by TheFanatr** [comment]
Doesn't work for me either.

**Comment by aelij** [comment]
Closing as it doesn't seem possible

**Comment by go-live-tech** [comment]
Actually calling private member does work

**Comment by go-live-tech** [comment]
Actually calling private member does work. There's another package similar to this one, [MakeTypesPublic](https://github.com/Denis535/MakeTypesPublic), which works flawlessly with private members.
